### PR TITLE
Added build script.

### PR DESCRIPTION
**Pull request by Preetam-Das**

### CODE REVIEW

**Comment by Preetam-Das** [comment]
@Debarka-Kundu @XanuduBuster Review plz.

**Comment by Debarka-Kundu** [comment]
@Preetam-Das come to discord

**Comment by Debarka-Kundu** [comment]
@Preetam-Das add a part in build script where if the user who is building does not have `chaotic-aur` installed, they will be prompted that 'do you want to install chaotic-aur? Its needed to build aerOS properly' like that...

**Comment by Preetam-Das** [comment]
@Debarka-Kundu done.

**Comment by Debarka-Kundu** [comment]
@Preetam-Das on the last command that it executues to install aur add --noconfirm at the end of the last command

**Comment by Debarka-Kundu** [comment]
@Preetam-Das the reason for that is it is not needed to press enter jey, onces it finishes installing it will start building

**Pull request merged**
